### ISSUE TITLE
Create tests

### ISSUE THREAD

**Issue by schempy** [cyclejs-community/cycle-canvas#10]

**Comment by Widdershin** [comment]
@schempy I had a thought about this. We could test this by stubbing out the canvas and checking it's called correctly, or we could break the driver up so that it has two functions, one to turn the virtual canvas tree into an array of canvas operations, and another to execute the canvas operations.

We could then just test that the virtual tree gets transformed into the right operations, which would make everything a bit easier. We could also then potentially do optimizations in future on the list of operations, such as removing duplicate font/color instructions.

**Comment by schempy** [comment]
Testing if the virtual tree gets transformed is a really good idea! I'll start stubbing out the canvas but I do like the idea of breaking the driver up.

**Comment by schempy** [comment]
@Widdershin I'm having trouble stubbing out the canvas. I'm using mocha and sinon. Could you provide an example to get me started? 

Thanks!
